pipeline {
    agent any

    environment {
        
        ARM_CLIENT_ID = credentials('azure-client-id')   
        ARM_CLIENT_SECRET = credentials('azure-client-secret') 
        ARM_TENANT_ID = credentials('azure-tenant-id')   
        ARM_SUBSCRIPTION_ID = credentials('azure-subscription-id')

          }

    stages {
        stage('Checkout') {
            steps {
                
                
               
                git branch: 'main', url: 'https://github.com/fasil916/terraform-deployment-assignment.git'
            }
        }

      stage('Terraform Code Scan') {
            steps {
                script {
                    echo "Running Terraform code scan using Checkov..."
                   
                   dir('terraform') {
                    sh '''
                        checkov -d . --output json > checkov-report.json || echo "Checkov scan completed with issues, but continuing the pipeline."
                    '''
                   }
                }
                }
            }
        

        stage('Azure Authentication') {
            steps {
                script {
               
                    sh '''
                        az login --service-principal -u ${ARM_CLIENT_ID} -p ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID}
                        az account set --subscription ${ARM_SUBSCRIPTION_ID}
                    '''
                
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                     dir('terraform') {
                    
                    sh 'terraform init'
                     }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    
                     dir('terraform') {
                   
                    sh 'terraform plan -out=tfplan'
                     }
                }
            }
        }

        stage('Terraform Apply') {
            
            steps {
                script {
                    dir('terraform') {
                   
                    sh 'terraform destroy -auto-approve tfplan'
                }
            }
        }
        }

        stage('Post-Deployment') {
            steps {
                script {
                  
                    echo "Terraform deployment complete!"
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after the job
            cleanWs()
        }
        success {
            echo 'Azure Terraform deployment succeeded!'
        }
        failure {
            echo 'Azure Terraform deployment failed!'
        }
     }
}
